// This file is auto-generated by the RevenueCat integration.
// It provides an authenticated client for the RevenueCat REST API.
// NEVER use this on the client side — server/scripts only.

import { createClient } from "@replit/revenuecat-sdk";

const REVENUECAT_PROJECT_ID = process.env.REVENUECAT_PROJECT_ID;

export async function getUncachableRevenueCatClient() {
  const hostname = process.env.REPLIT_CONNECTORS_HOSTNAME;
  const replIdentity = process.env.REPL_IDENTITY;
  const webReplRenewal = process.env.WEB_REPL_RENEWAL;

  if (!hostname || !replIdentity) {
    throw new Error(
      "RevenueCat connector not configured. Connect RevenueCat via the Replit integrations panel."
    );
  }

  const tokenRes = await fetch(
    `https://${hostname}/api/v2/connection/token`,
    {
      headers: {
        Authorization: `Bearer ${replIdentity}`,
        "X-Replit-Renewal": webReplRenewal ?? "",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ connector_config_id: "ccfg_revenuecat_01KED80FZSMH99H5FHQWSX7D4M" }),
      method: "POST",
    }
  );

  if (!tokenRes.ok) {
    throw new Error(`Failed to get RevenueCat token: ${tokenRes.status} ${await tokenRes.text()}`);
  }

  const { token } = (await tokenRes.json()) as { token: string };

  return createClient({ token });
}
